version: '3'

services:
  database:
    image: "postgres"
    container_name: "database"
    volumes:
      - ./database:/data/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: estantevirtual
  cache:
    image: redis:latest
    container_name: "cache"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data/cache
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8080:8080"
    links:
      - cache
    depends_on:
      - database
      - cache