version: '3'

services:
  db:
    image: "postgres"
    container_name: "db"
    volumes:
      - ./db:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: estantevirtual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9V%=JftDf<
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8080:8080"
    depends_on:
      - db